CREATE TABLE IF NOT EXISTS mpas (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(10) UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS genres (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(50) UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(200) NOT NULL,
    release_year DATE NOT NULL,
    rate integer NOT NULL,
    duration integer NOT NULL,
    mpas_id integer NOT NULL,
    CONSTRAINT films_fk FOREIGN KEY (mpas_id) REFERENCES mpas (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_genres (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	film_id INTEGER NOT NULL,
	genre_id varchar(50) NOT NULL,
	CONSTRAINT film_genres_fk FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
	CONSTRAINT film_genres_fk1 FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(50) NOT NULL,
	login varchar(50) NOT NULL,
	name varchar(50) NOT NULL,
	birthday DATE NOT NULL
);
CREATE TABLE IF NOT EXISTS likes (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	film_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	grade INTEGER NOT NULL,
	CONSTRAINT likes_fk FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
	CONSTRAINT likes_fk1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
	CONSTRAINT likes_unique UNIQUE (film_id, user_id)
);
CREATE TABLE IF NOT EXISTS friends (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    status varchar(50) NOT NULL CHECK (status = 'Confirmed' OR status = 'Unconfirmed'),
    CONSTRAINT friends_fk1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT friends_fk2 FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT friends_unique UNIQUE (user_id, friend_id)
);





